SET NOCOUNT ON;

DECLARE @landlord_id UNIQUEIDENTIFIER = (
    SELECT TOP 1 id FROM dbo.users WHERE email = N'ci.landlord@sichrplace.test'
);

IF @landlord_id IS NULL
BEGIN
    SET @landlord_id = NEWID();
    INSERT INTO dbo.users (id, email, password_hash, role, first_name, last_name, username)
    VALUES (
        @landlord_id,
        N'ci.landlord@sichrplace.test',
        N'ci-hash',
        N'landlord',
        N'CI',
        N'Landlord',
        N'ci_landlord'
    );
END;

DECLARE @tenant_id UNIQUEIDENTIFIER = (
    SELECT TOP 1 id FROM dbo.users WHERE email = N'ci.tenant@sichrplace.test'
);

IF @tenant_id IS NULL
BEGIN
    SET @tenant_id = NEWID();
    INSERT INTO dbo.users (id, email, password_hash, role, first_name, last_name, username)
    VALUES (
        @tenant_id,
        N'ci.tenant@sichrplace.test',
        N'ci-hash',
        N'tenant',
        N'CI',
        N'Tenant',
        N'ci_tenant'
    );
END;

DECLARE @apartment_id UNIQUEIDENTIFIER = (
    SELECT TOP 1 a.id
    FROM dbo.apartments a
    WHERE a.landlord_id = @landlord_id
      AND a.title = N'CI Smoke Apartment'
);

IF @apartment_id IS NULL
BEGIN
    SET @apartment_id = NEWID();
    INSERT INTO dbo.apartments (id, landlord_id, title, description, city, address, rent_amount, rooms, size_sqm, status)
    VALUES (
        @apartment_id,
        @landlord_id,
        N'CI Smoke Apartment',
        N'Autogenerated seed for smoke verification.',
        N'Berlin',
        N'CI Street 1',
        1000.00,
        2,
        55.0,
        N'available'
    );
END;

DECLARE @conversation_id UNIQUEIDENTIFIER = (
    SELECT TOP 1 c.id
    FROM dbo.conversations c
    WHERE c.apartment_id = @apartment_id
      AND c.landlord_id = @landlord_id
      AND c.tenant_id = @tenant_id
);

IF @conversation_id IS NULL
BEGIN
    SET @conversation_id = NEWID();
    INSERT INTO dbo.conversations (id, apartment_id, landlord_id, tenant_id)
    VALUES (@conversation_id, @apartment_id, @landlord_id, @tenant_id);
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.messages
    WHERE conversation_id = @conversation_id
      AND sender_id = @tenant_id
      AND content = N'CI smoke message from tenant'
)
BEGIN
    INSERT INTO dbo.messages (id, conversation_id, sender_id, content)
    VALUES (NEWID(), @conversation_id, @tenant_id, N'CI smoke message from tenant');
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.messages
    WHERE conversation_id = @conversation_id
      AND sender_id = @landlord_id
      AND content = N'CI smoke reply from landlord'
)
BEGIN
    INSERT INTO dbo.messages (id, conversation_id, sender_id, content)
    VALUES (NEWID(), @conversation_id, @landlord_id, N'CI smoke reply from landlord');
END;
