-- =============================================================================
-- V001__initial_schema_mssql.sql
-- SichrPlace — Baseline schema for MSSQL 2025 Developer Edition
--
-- Purpose:   Documents the 9-table schema as generated by Hibernate
--            ddl-auto=update from JPA entity annotations.
--            This script is IDEMPOTENT — safe to run multiple times.
--
-- Generated: February 2026
-- Source:    JPA entities in com.sichrplace.backend.model.*
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. users
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'users')
BEGIN
    CREATE TABLE users (
        id              BIGINT          IDENTITY(1,1)   NOT NULL,
        email           VARCHAR(255)    NOT NULL,
        password        VARCHAR(255)    NOT NULL,
        first_name      VARCHAR(255)    NULL,
        last_name       VARCHAR(255)    NULL,
        bio             VARCHAR(MAX)    NULL,
        phone           VARCHAR(255)    NULL,
        role            VARCHAR(255)    NOT NULL,
        email_verified  BIT             NULL,
        profile_image_url VARCHAR(255)  NULL,
        city            VARCHAR(255)    NULL,
        country         VARCHAR(255)    NULL,
        is_active       BIT             NULL,
        last_login_at   DATETIME2       NULL,
        gdpr_consent    BIT             NULL,
        gdpr_consent_date DATETIME2     NULL,
        marketing_consent BIT           NULL,
        created_at      DATETIME2       NULL,
        updated_at      DATETIME2       NULL,

        CONSTRAINT pk_users PRIMARY KEY (id),
        CONSTRAINT uq_user_email UNIQUE (email)
    );

    CREATE INDEX idx_user_email      ON users (email);
    CREATE INDEX idx_user_role       ON users (role);
    CREATE INDEX idx_user_created_at ON users (created_at);

    PRINT 'Created table: users';
END
ELSE
    PRINT 'Table users already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 2. apartments
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'apartments')
BEGIN
    CREATE TABLE apartments (
        id                  BIGINT          IDENTITY(1,1)   NOT NULL,
        user_id             BIGINT          NOT NULL,
        title               VARCHAR(255)    NOT NULL,
        description         VARCHAR(MAX)    NULL,
        city                VARCHAR(255)    NOT NULL,
        district            VARCHAR(255)    NULL,
        address             VARCHAR(255)    NULL,
        latitude            FLOAT           NULL,
        longitude           FLOAT           NULL,
        monthly_rent        DECIMAL(10,2)   NOT NULL,
        deposit_amount      DECIMAL(10,2)   NULL,
        size_square_meters  FLOAT           NULL,
        number_of_bedrooms  INT             NULL,
        number_of_bathrooms INT             NULL,
        furnished           BIT             NULL,
        pet_friendly        BIT             NULL,
        has_parking         BIT             NULL,
        has_elevator        BIT             NULL,
        has_balcony         BIT             NULL,
        amenities           VARCHAR(MAX)    NULL,
        available_from      DATE            NULL,
        status              VARCHAR(255)    NOT NULL,
        number_of_views     BIGINT          NULL,
        average_rating      FLOAT           NULL,
        review_count        INT             NULL,
        created_at          DATETIME2       NULL,
        updated_at          DATETIME2       NULL,

        CONSTRAINT pk_apartments PRIMARY KEY (id),
        CONSTRAINT fk_apartment_owner FOREIGN KEY (user_id) REFERENCES users(id)
    );

    CREATE INDEX idx_apartment_owner      ON apartments (user_id);
    CREATE INDEX idx_apartment_status     ON apartments (status);
    CREATE INDEX idx_apartment_city       ON apartments (city);
    CREATE INDEX idx_apartment_district   ON apartments (district);
    CREATE INDEX idx_apartment_created_at ON apartments (created_at);

    PRINT 'Created table: apartments';
END
ELSE
    PRINT 'Table apartments already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 3. listings
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'listings')
BEGIN
    CREATE TABLE listings (
        id                  BIGINT          IDENTITY(1,1)   NOT NULL,
        title               VARCHAR(255)    NOT NULL,
        description         VARCHAR(MAX)    NULL,
        city                VARCHAR(100)    NOT NULL,
        district            VARCHAR(100)    NULL,
        monthly_rent        DECIMAL(10,2)   NOT NULL,
        size_square_meters  FLOAT           NULL,
        furnished           BIT             NULL,
        available_from      DATE            NULL,
        created_at          DATETIME2       NOT NULL,
        updated_at          DATETIME2       NOT NULL,
        owner_id            BIGINT          NOT NULL,

        CONSTRAINT pk_listings PRIMARY KEY (id)
    );

    PRINT 'Created table: listings';
END
ELSE
    PRINT 'Table listings already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 4. conversations
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'conversations')
BEGIN
    CREATE TABLE conversations (
        id                BIGINT      IDENTITY(1,1)   NOT NULL,
        apartment_id      BIGINT      NULL,
        participant_1_id  BIGINT      NOT NULL,
        participant_2_id  BIGINT      NOT NULL,
        last_message_at   DATETIME2   NULL,
        created_at        DATETIME2   NULL,
        updated_at        DATETIME2   NULL,

        CONSTRAINT pk_conversations PRIMARY KEY (id),
        CONSTRAINT fk_conv_apartment FOREIGN KEY (apartment_id)  REFERENCES apartments(id),
        CONSTRAINT fk_conv_p1        FOREIGN KEY (participant_1_id) REFERENCES users(id),
        CONSTRAINT fk_conv_p2        FOREIGN KEY (participant_2_id) REFERENCES users(id),
        CONSTRAINT uq_conversation_participants_apartment
            UNIQUE (apartment_id, participant_1_id, participant_2_id)
    );

    CREATE INDEX idx_conv_p1       ON conversations (participant_1_id);
    CREATE INDEX idx_conv_p2       ON conversations (participant_2_id);
    CREATE INDEX idx_conv_apartment ON conversations (apartment_id);
    CREATE INDEX idx_conv_last_msg  ON conversations (last_message_at);

    PRINT 'Created table: conversations';
END
ELSE
    PRINT 'Table conversations already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 5. messages
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'messages')
BEGIN
    CREATE TABLE messages (
        id                BIGINT          IDENTITY(1,1)   NOT NULL,
        conversation_id   BIGINT          NOT NULL,
        sender_id         BIGINT          NOT NULL,
        content           VARCHAR(MAX)    NOT NULL,
        message_type      VARCHAR(20)     NOT NULL,
        read_by_recipient BIT             NULL    DEFAULT 0,
        read_at           DATETIME2       NULL,
        file_url          VARCHAR(255)    NULL,
        file_name         VARCHAR(255)    NULL,
        file_size         INT             NULL,
        is_deleted        BIT             NULL    DEFAULT 0,
        edited_at         DATETIME2       NULL,
        created_at        DATETIME2       NULL,

        CONSTRAINT pk_messages PRIMARY KEY (id),
        CONSTRAINT fk_msg_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
        CONSTRAINT fk_msg_sender       FOREIGN KEY (sender_id)       REFERENCES users(id)
    );

    CREATE INDEX idx_msg_conversation ON messages (conversation_id);
    CREATE INDEX idx_msg_sender       ON messages (sender_id);
    CREATE INDEX idx_msg_created_at   ON messages (created_at);

    PRINT 'Created table: messages';
END
ELSE
    PRINT 'Table messages already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 6. viewing_requests
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'viewing_requests')
BEGIN
    CREATE TABLE viewing_requests (
        id                  BIGINT          IDENTITY(1,1)   NOT NULL,
        apartment_id        BIGINT          NOT NULL,
        tenant_id           BIGINT          NOT NULL,
        proposed_date_time  DATETIME2       NOT NULL,
        message             VARCHAR(MAX)    NULL,
        status              VARCHAR(255)    NOT NULL,
        responded_at        DATETIME2       NULL,
        confirmed_date_time DATETIME2       NULL,
        decline_reason      VARCHAR(255)    NULL,
        created_at          DATETIME2       NULL,
        updated_at          DATETIME2       NULL,

        CONSTRAINT pk_viewing_requests PRIMARY KEY (id),
        CONSTRAINT fk_vr_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id),
        CONSTRAINT fk_vr_tenant    FOREIGN KEY (tenant_id)    REFERENCES users(id)
    );

    CREATE INDEX idx_vr_tenant     ON viewing_requests (tenant_id);
    CREATE INDEX idx_vr_apartment  ON viewing_requests (apartment_id);
    CREATE INDEX idx_vr_status     ON viewing_requests (status);
    CREATE INDEX idx_vr_created_at ON viewing_requests (created_at);

    PRINT 'Created table: viewing_requests';
END
ELSE
    PRINT 'Table viewing_requests already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 7. apartment_reviews
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'apartment_reviews')
BEGIN
    CREATE TABLE apartment_reviews (
        id                BIGINT          IDENTITY(1,1)   NOT NULL,
        apartment_id      BIGINT          NOT NULL,
        reviewer_id       BIGINT          NOT NULL,
        rating            INT             NOT NULL,
        title             VARCHAR(255)    NOT NULL,
        comment           VARCHAR(MAX)    NOT NULL,
        pros              VARCHAR(MAX)    NULL,
        cons              VARCHAR(MAX)    NULL,
        would_recommend   BIT             NULL,
        landlord_rating   INT             NULL,
        location_rating   INT             NULL,
        value_rating      INT             NULL,
        status            VARCHAR(255)    NOT NULL,
        moderated_by      BIGINT          NULL,
        moderated_at      DATETIME2       NULL,
        moderation_notes  VARCHAR(MAX)    NULL,
        created_at        DATETIME2       NULL,
        updated_at        DATETIME2       NULL,

        CONSTRAINT pk_apartment_reviews PRIMARY KEY (id),
        CONSTRAINT fk_review_apartment  FOREIGN KEY (apartment_id) REFERENCES apartments(id),
        CONSTRAINT fk_review_reviewer   FOREIGN KEY (reviewer_id)  REFERENCES users(id),
        CONSTRAINT fk_review_moderator  FOREIGN KEY (moderated_by) REFERENCES users(id),
        CONSTRAINT uq_apartment_reviewer UNIQUE (apartment_id, reviewer_id)
    );

    CREATE INDEX idx_review_apartment  ON apartment_reviews (apartment_id);
    CREATE INDEX idx_review_reviewer   ON apartment_reviews (reviewer_id);
    CREATE INDEX idx_review_status     ON apartment_reviews (status);
    CREATE INDEX idx_review_created_at ON apartment_reviews (created_at);

    PRINT 'Created table: apartment_reviews';
END
ELSE
    PRINT 'Table apartment_reviews already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 8. user_favorites
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'user_favorites')
BEGIN
    CREATE TABLE user_favorites (
        id            BIGINT      IDENTITY(1,1)   NOT NULL,
        user_id       BIGINT      NOT NULL,
        apartment_id  BIGINT      NOT NULL,
        created_at    DATETIME2   NULL,

        CONSTRAINT pk_user_favorites PRIMARY KEY (id),
        CONSTRAINT fk_fav_user      FOREIGN KEY (user_id)      REFERENCES users(id),
        CONSTRAINT fk_fav_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id),
        CONSTRAINT uq_user_apartment_favorite UNIQUE (user_id, apartment_id)
    );

    CREATE INDEX idx_fav_user      ON user_favorites (user_id);
    CREATE INDEX idx_fav_apartment ON user_favorites (apartment_id);

    PRINT 'Created table: user_favorites';
END
ELSE
    PRINT 'Table user_favorites already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- 9. notifications
-- ---------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'notifications')
BEGIN
    CREATE TABLE notifications (
        id                    BIGINT          IDENTITY(1,1)   NOT NULL,
        user_id               BIGINT          NOT NULL,
        type                  VARCHAR(50)     NOT NULL,
        title                 VARCHAR(255)    NOT NULL,
        message               VARCHAR(MAX)    NULL,
        related_entity_type   VARCHAR(50)     NULL,
        related_entity_id     BIGINT          NULL,
        read_at               DATETIME2       NULL,
        action_url            VARCHAR(255)    NULL,
        priority              VARCHAR(20)     NOT NULL    DEFAULT 'NORMAL',
        created_at            DATETIME2       NULL,
        expires_at            DATETIME2       NULL,

        CONSTRAINT pk_notifications PRIMARY KEY (id),
        CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id)
    );

    CREATE INDEX idx_notif_user       ON notifications (user_id);
    CREATE INDEX idx_notif_read_at    ON notifications (read_at);
    CREATE INDEX idx_notif_type       ON notifications (type);
    CREATE INDEX idx_notif_created_at ON notifications (created_at);

    PRINT 'Created table: notifications';
END
ELSE
    PRINT 'Table notifications already exists — skipping.';
GO

-- ---------------------------------------------------------------------------
-- Summary
-- ---------------------------------------------------------------------------
PRINT '═══════════════════════════════════════════════════════';
PRINT '  V001 — Initial schema check complete.';
PRINT '  9 tables: users, apartments, listings, conversations,';
PRINT '            messages, viewing_requests, apartment_reviews,';
PRINT '            user_favorites, notifications';
PRINT '═══════════════════════════════════════════════════════';
GO
